execfile("/home/gchenming/Dropbox/scripts/github/ecmwf_reader/python/class_station.py")
a=Station('asdf')
a.find_lats_lons_idx_from_mtx(lats,lons) 
a.extract_value_at_stations(evap_yearly_raw,rain_yearly_raw,lats,lons,day_count_yearly)
a.interpolate_values_as_mtx(lats,lons)
